// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.Data.EF;

namespace ProjectName.Data.Migrations
{
    [DbContext(typeof(ProjectNameDbContext))]
    [Migration("20220130051235_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectName.Data.Entities.Role", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRole");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUserDetail")
                        .HasColumnType("int");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.UserDetail", b =>
                {
                    b.Property<int>("idUserDetail")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateDay")
                        .HasColumnType("datetime2");

                    b.HasKey("idUserDetail");

                    b.ToTable("UserDetail");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.HasKey("idUser", "idRole");

                    b.HasIndex("idRole");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.UserDetail", b =>
                {
                    b.HasOne("ProjectName.Data.Entities.User", "user")
                        .WithOne("userDetail")
                        .HasForeignKey("ProjectName.Data.Entities.UserDetail", "idUserDetail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.UserRole", b =>
                {
                    b.HasOne("ProjectName.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectName.Data.Entities.User", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjectName.Data.Entities.User", b =>
                {
                    b.Navigation("userDetail");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
